language: csharp
mono: none
solution: MyCsharpProject.sln
dotnet: 3.1.200
script:
 - dotnet restore

 install:
  - nuget restore MyCsharpProject.sln
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
